sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t webmapp/gdal-docker:latest .
  - docker run -it webmapp/gdal-docker:latest ogrinfo --version
  - docker run -it webmapp/gdal-docker:latest ogr2ogr --formats
